#!/bin/bash

GIT_DESCRIBE=`git describe --tags`

VER_NUMBERS=`echo $GIT_DESCRIBE | sed 's/[^[[:digit:]]]*\([[:digit:]]\+\)\.\([[:digit:]]\+\)\.\([[:digit:]]\+\).*/\1 \2 \3/'`

MAJOR=`echo $VER_NUMBERS | cut -d ' ' -f 1`
MINOR=`echo $VER_NUMBERS | cut -d ' ' -f 2`
PATCH=`echo $VER_NUMBERS | cut -d ' ' -f 3`

VERSION_CODE=$((MAJOR * 1000000 + MINOR * 1000 + PATCH))
VERSION_NAME=$GIT_DESCRIBE

mkdir bin

cat AndroidManifest.xml \
    | sed "s/\(android:versionCode=\)\"[[:digit:]]*\"/\1\"$VERSION_CODE\"/" \
    | sed "s/\(android:versionName=\)\".*\"\+/\1\"$VERSION_NAME\"/" \
    > bin/AndroidManifest.xml

echo -e \
"`readlink -f bin/AndroidManifest.xml` : \\
`readlink -f AndroidManifest.xml` \\" \
    > bin/AndroidManifest.xml.d
