#!/bin/bash

echo -e "package com.Chris.NetTool;\n\npublic class Version {\n    public final static String sVersion;\n\n    static {\n        sVersion = \"$(git describe --tags)\";\n    }\n};" > src/com/Chris/NetTool/Version.java
